name: Publish Gem

on:
  release:
    types: [published]

jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment: release

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.245.0
      with:
        ruby-version: 3.4

    - name: Publish to RubyGems
      uses: rubygems/release-gem@v1
